# Generated by Django 5.0.7 on 2024-08-03 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_servicecontact_solutioncontact'),
        ('services', '0014_service_firstword'),
        ('solutions', '0008_rename_image1_solutiongallery_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutioncontact',
            name='solution',
        ),
        migrations.AddField(
            model_name='contact',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='services.service'),
        ),
        migrations.AddField(
            model_name='contact',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='solutions.solution'),
        ),
        migrations.DeleteModel(
            name='ServiceContact',
        ),
        migrations.DeleteModel(
            name='SolutionContact',
        ),
    ]
