# Generated by Django 5.0.7 on 2024-07-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_solution_created_by_solution_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutionattribute',
            old_name='value',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='solutionattribute',
            old_name='key',
            new_name='title',
        ),
    ]
