# Generated by Django 5.0.7 on 2024-07-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_rename_name_solution_intro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutiongallery',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='solutiongallery',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='solutiongallery',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='solutiongallery',
            name='image4',
        ),
    ]
