# Generated by Django 5.0.7 on 2024-08-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0008_rename_image1_solutiongallery_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='datafile',
            field=models.FileField(blank=True, null=True, upload_to='solutions/datasheets/'),
        ),
    ]
