# Generated by Django 5.0.7 on 2024-08-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0009_solution_datafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='datafile',
            field=models.FileField(blank=True, null=True, upload_to='solutions/datafiles/'),
        ),
    ]
