# Generated by Django 5.0.7 on 2024-07-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_created_by_service_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedeploymentstep',
            name='step_number',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
