# Generated by Django 5.0.7 on 2024-07-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicedeploymentstep_step_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicedeploymentstep',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='servicedeploymentstep',
            name='step_number',
            field=models.PositiveIntegerField(),
        ),
    ]
