# Generated by Django 5.0.7 on 2024-07-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicedeploymentstep_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedeploymentstep',
            old_name='step_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='servicedeploymentstep',
            old_name='step_title',
            new_name='title',
        ),
    ]
