# Generated by Django 5.0.7 on 2024-07-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_service_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='intro',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='servicedeploymentstep',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='service',
            name='detail_image',
            field=models.ImageField(default=1, upload_to='services/detail_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='intro_image',
            field=models.ImageField(default=1, upload_to='services/intro_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicedeploymentstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='solutions/details/'),
        ),
    ]
