# Generated by Django 5.0.7 on 2024-07-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicedeploymentstep_step_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedeploymentstep',
            name='step_number',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='servicedeploymentstep',
            unique_together={('service', 'step_number')},
        ),
    ]
