# Generated by Django 5.0.7 on 2024-07-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicedeploymentstep_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedeploymentstep',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='servicedeploymentstep',
            name='step_number',
        ),
    ]
