# Generated by Django 5.0.7 on 2024-07-24 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_rename_description_service_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/detail_images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/intro_images/'),
        ),
        migrations.AlterField(
            model_name='servicedeploymentstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/step_images'),
        ),
        migrations.CreateModel(
            name='ServiceCompetitiveAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitive_advantages_list', to='services.service')),
            ],
        ),
    ]
