# Generated by Django 5.0.7 on 2024-07-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_service_description_alter_service_detail_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='competitive_advantages',
        ),
        migrations.AlterField(
            model_name='servicecompetitiveadvantage',
            name='content',
            field=models.TextField(),
        ),
    ]
