# Generated by Django 5.0.7 on 2024-07-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_remove_service_competitive_advantages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='firstword',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
    ]
