# Generated by Django 5.0.7 on 2024-07-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_rename_value_solutionattribute_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
