# Generated by Django 5.0.7 on 2024-07-24 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0006_alter_solution_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='name',
            new_name='intro',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='description',
        ),
        migrations.AddField(
            model_name='solution',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='solutions/intro_images/'),
        ),
        migrations.AddField(
            model_name='solution',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SolutionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='solutions/details/')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='solutions.solution')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='solutions/gallery/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='solutions/gallery/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='solutions/gallery/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='solutions/gallery/')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='solutions.solution')),
            ],
        ),
        migrations.DeleteModel(
            name='SolutionAttribute',
        ),
    ]
